theme = "catppuccin_frappe"

[editor]
auto-format = false
auto-pairs = false
auto-save = true
# completion-replace = true
cursorline = true
idle-timeout = 0
rulers = [100]
text-width = 100

[editor.lsp]
goto-reference-include-declaration = false

[editor.cursor-shape]
insert = "bar"

[editor.smart-tab]
supersede-menu = true

[keys.normal.space]
space = "file_picker"
"," = "buffer_picker"

[editor.whitespace.render]
newline = "all"
