[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
# format = true
nodePath = ""
# onIgnoredFiles = "off"
# packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
# useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
# codeActionsOnSave = { mode = "all" }
experimental = {}
problems = { shortenToSingleLine = false }
# workingDirectory = { mode = "auto" }

# [language-server.jdtls]
# args = ["--jvm-arg=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=1044"]

[language-server.jdtls.config.java.autobuild]
enabled = true

[language-server.jdtls.config.java.completion]
maxResults = 1000

[language-server.jdtls.config.java.format.settings]
url = "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml"

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "eslint" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "eslint" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }
